[package]
name = "ahmoin/freeze"
authors = ["ahmoin"]
description = "Immutable data structures for Roblox Luau ❄️"
version = "0.1.4"
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"
exclude = [
    "bin",
    "docs",
    ".moonwave",
    "build",
    "tests",
    "*spec.luau",
    "*.d.luau",
]

[dependencies]
